### ISSUE TITLE
Localization Error on osx

### ISSUE THREAD

**Issue by juukas** [mls-m5/neo-font-editor#2]
I get an error: `libc++abi.dylib: terminating with uncaught exception of type std::runtime_error: collate_byname<char>::collate_byname failed to construct for sv_SE.UTF8`
When running this command: `font_editor xxx.os3kapp -f font-data.txt`
(I am running MacOS Catalina).

My knowledge around building in cmake is extremely limited and I am sorry if made an obvious mistake. I have a Swedish Neo2 that unfortunaly came flashed with UK software, so I am trying to make all of the characters on the keyboard to become 100% swedish, since the physical layout is swedish. The fonts I found online have correct swedish layout for the characters but not for all of the special characters.

**Comment by mls-m5** [comment]
Hi, nice that you have tried the library.. What operating system do you run? Windows, linux or something else?

**Comment by mls-m5** [comment]
Interesting. I have not tried to compile to mac yet.

~~Does it work if you find "sv_SE.UTF-8" (in src/alpha.h) and change it to  "sv_SE.UTF8" (with minus sign) or change to "en_US.UTF-8"~~

I might have messed that up, but on my linux machine it works. If it works better with any of the others I could change to them.

**Comment by mls-m5** [comment]
Hmm.. Some notes for me.. https://stackoverflow.com/questions/1745045/stdlocale-breakage-on-macos-10-6-with-lang-en-us-utf-8

**Comment by mls-m5** [comment]
Created pull request #3

**Comment by mls-m5** [comment]
Does it work now if you try to downoad the latest changes? @juukas

**Comment by juukas** [comment]
@mls-m5 thank you for looking into it! I will check it out and report when I get back home ~tuesday.

**Comment by mls-m5** [comment]
Nice.

By the way, I forgot to mention. Maybe I should have put a link in the readme aswell.

While making this program I got some swedish fonts from another guy in a Facebook group. I really appreciate to have someone more that tests out the library, but if you do not get it to work, you could try some of these fonts:

https://github.com/mls-m5/alphasmart-neo-backup/tree/master/extra-fonts

**Comment by mls-m5** [comment]
@juukas  I think it is time to close this issue. Btw. I am working on a web based editor if you are interested in that in the future.
